Ogni modello/tokenizer può essere richiamato con la sua classe o tramite la autoclass, che automaticamente instanzia l'oggetto corrispondente al nome del modello:

```
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name)
```

Dalla [documentazione](https://huggingface.co/docs/transformers/index) potete vedere tutte le classi e i modelli disponibili. Per il caricamento di un modello via autoclass di cui conoscete il nome ma non l'esatta dicitura, cerca il modello su [huggingface](https://huggingface.co/), vai sulla scheda del modello con il nome per il caricamento sul codice python, con descrizione e codice di esempio (vedi la [scheda](https://huggingface.co/roberta-base) di RoBERTa il cui nome del modello da inserire nel codice è `roberta-base`)

In [ ]:
from transformers import AutoConfig, AutoModel, AutoTokenizer

model_name = "bert-base-uncased"
config = AutoConfig.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name, config=config)

In [ ]:
# come funziona il tokenizzatore di BERT

s = 'The quick brown fox, jumps over: the lazy dog.'
print(len(s))
print(s)
print(len(tokenizer.tokenize(s)))
print(tokenizer.tokenize(s)) # è la lista delle parole tokenizzate

46
The quick brown fox, jumps over: the lazy dog.
12
['the', 'quick', 'brown', 'fox', ',', 'jumps', 'over', ':', 'the', 'lazy', 'dog', '.']


In [ ]:
# tk = tokenizer(s, add_special_tokens=True, return_tensors="pt")
# restituisce un dizionario con i seguenti campi
# input_ids -> tokens numerici
# token_type_ids -> se 0 è la prima frase, se è 1 è la  seconda [CLS]
# sentence 1 [SEP] sentence 2
# attention_mask -> 1 se c'è un token in posizione, si vede meglio sotto quando
# passo una lista di frasi da processare

print('--- tensors ---')

tk = tokenizer(s, add_special_tokens=True, return_tensors="pt")
print(tk['input_ids'].shape)
print(type(tk['input_ids']))
print(tk['input_ids'])
print('*********')
print(tk['attention_mask'].shape)
print(type(tk['attention_mask']))
print(tk['attention_mask'])

print('--- no tensors ---')

tk = tokenizer(s, add_special_tokens=False)
print(len(tk['input_ids']))
print(type(tk['input_ids']))
print(tk['input_ids'])
print('*********')
print(len(tk['attention_mask']))
print(type(tk['attention_mask']))
print(tk['attention_mask'])

--- tensors ---
torch.Size([1, 14])
<class 'torch.Tensor'>
tensor([[  101,  1996,  4248,  2829,  4419,  1010, 14523,  2058,  1024,  1996,
         13971,  3899,  1012,   102]])
*********
torch.Size([1, 14])
<class 'torch.Tensor'>
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
--- no tensors ---
12
<class 'list'>
[1996, 4248, 2829, 4419, 1010, 14523, 2058, 1024, 1996, 13971, 3899, 1012]
*********
12
<class 'list'>
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
s = ['The quick brown fox',
     'jumps over: t',
     'The quick brown fox, jumps']

tk_1 = tokenizer(s, add_special_tokens=True, return_tensors="pt", padding=True)
tk_2 = tokenizer(s, add_special_tokens=False, return_tensors="pt", padding=True)
print(tk_1['input_ids'].shape)
print(type(tk_1['input_ids']))
print(tk_1['input_ids'])
print('----')
print(tk_2['input_ids'].shape)
print(type(tk_2['input_ids']))
print(tk_2['input_ids'])


torch.Size([3, 8])
<class 'torch.Tensor'>
tensor([[  101,  1996,  4248,  2829,  4419,   102,     0,     0],
        [  101, 14523,  2058,  1024,  1056,   102,     0,     0],
        [  101,  1996,  4248,  2829,  4419,  1010, 14523,   102]])
----
torch.Size([3, 6])
<class 'torch.Tensor'>
tensor([[ 1996,  4248,  2829,  4419,     0,     0],
        [14523,  2058,  1024,  1056,     0,     0],
        [ 1996,  4248,  2829,  4419,  1010, 14523]])


In [ ]:
outputs = model(tk['input_ids'], attention_mask=tk['input_ids'])
last_hidden_states = outputs.last_hidden_state
print(last_hidden_states.shape)
# (n, l, d)
    # n batch size
    # l max len (padding value)
    # d emb size
print(last_hidden_states)
#print(outputs)

torch.Size([1, 14, 768])
tensor([[[-0.0758,  0.0983,  0.1892,  ..., -0.0758,  0.1653,  0.1204],
         [-0.4688,  0.0442,  0.1436,  ...,  0.0519,  0.2204, -0.2437],
         [-0.1859,  0.0711,  0.1784,  ..., -0.1782,  0.2911,  0.1189],
         ...,
         [-0.1180,  0.2406,  0.1644,  ..., -0.2078,  0.2466,  0.4746],
         [-0.4778,  0.1236,  0.1518,  ..., -0.0455,  0.1276, -0.0518],
         [-0.3996,  0.2032,  0.1841,  ..., -0.0505,  0.1733,  0.1133]]],
       grad_fn=<NativeLayerNormBackward0>)


In [ ]:
print(model)

In [ ]:
from transformers import pipeline


model = "bert-base-uncased"
task = "feature-extraction"
tokenizer = AutoTokenizer.from_pretrained(model)


text = 'The quick brown fox, jumps over: the lazy dog.'
tokenized_text = tokenizer.tokenize(s)

feature_extractor = pipeline(task = task, model=model, tokenizer=tokenizer)
result = feature_extractor(s, return_tensors=True)
# con pipeline di hugging face fa la stessa cosa, estrae i cls token

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


In [ ]:
(result == last_hidden_states).all()

tensor(True)

In [ ]:
import pandas as pd
import sklearn
from tqdm import tqdm
import numpy as np
import nltk
from nltk.corpus import stopwords
from torch import nn
from torch.optim import Adam
import torch

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
# Dataset
# repository https://github.com/iresiragusa/NLP/tree/main
# https://www.kaggle.com/datasets/yufengdev/bbc-fulltext-and-category?select=bbc-text.csv
# scarichiamo il dataset e lo carichiamo su COLAB

root = "/content/gdrive/MyDrive/Colab Notebooks/torch/"
df = pd.read_csv(root+"data/BBC-text/bbc-text.csv")

In [ ]:
# il dataset è formato da 2225 sample contenenti aricoli della BBC
# suddivisi in 5 categorie in base al loro topic

print('n sample -> '+str(len(df)))
labels = set(df['category'])
print('categories -> '+str(labels)+'['+str(len(labels))+']')
print(df['category'].value_counts())

# associo ad ogni categoria un indice, così ho delle label numeriche
labels_dict = {
    'business': 0,
    'politics': 1,
    'tech': 2,
    'sport': 3,
    'entertainment': 4
}

df['labels'] = df.apply(lambda row: labels_dict[row.category], axis = 1)

In [ ]:
from sklearn.model_selection import train_test_split

(x_train, x_test, y_train, y_test) = train_test_split(df['text'], df['labels'], test_size=0.2, random_state=17)
(x_train, x_val, y_train, y_val) = train_test_split(x_train, y_train, test_size=0.1, random_state=17)

# sarebbe uno split 72, 8, 20 per avere lo stesso test dell'altra volta

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

class Dataset(torch.utils.data.Dataset):

    def __init__(self, x, y, stopwords):

        # x e y sono series di pandas
        tokens_litt = [nltk.word_tokenize(text, language='english')
         for text in list(x)]
        text_clean = []

        if stopwords:
            for sentence in tqdm(tokens_litt, desc='Tokenizing ... '):
                text_clean.append(' '.join([w.lower() for w in sentence if
                    not w.lower() in nltk.corpus.stopwords.words("english")]))
        else:
            for sentence in tqdm(tokens_litt, desc='Tokenizing ... '):
                text_clean.append(' '.join([w.lower() for w in sentence]))
            # ogni token è separato dall'altro con uno spazio

        self.texts = text_clean
        self.labels = [torch.tensor(label) for label in y]

    def classes(self):
        return self.labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):

        batch_texts = self.texts[idx]
        batch_labels = np.array(self.labels[idx])

        return batch_texts, batch_labels

In [ ]:
hyperparameters = {
    "epochs": 5,
    "learning_rate": 1e-3,
    "batch_size": 64,
    "dropout": 0.1,
    "stopwords": False,
    "language_model": "bert-base-uncased",
    "layers": 1,
    "h_dim": 768,
    "bilstm": True,
    "patience": 5,
    "min_delta": 0.01
}

In [ ]:
#creo i dataset

train_dataset = Dataset(x_train, y_train, hyperparameters["stopwords"])
val_dataset = Dataset(x_val, y_val, hyperparameters["stopwords"])
test_dataset = Dataset(x_test, y_test, hyperparameters["stopwords"])

In [ ]:
# classe della rete

class ClassifierDeep(nn.Module):

    def __init__(self, labels, hdim, dropout):
        super(ClassifierDeep, self).__init__()
        self.classifier = nn.Sequential(
            nn.Linear(hdim, hdim),
            nn.BatchNorm1d(hdim),
            nn.Dropout(dropout),
            nn.ReLU(),
            nn.Linear(hdim, labels),
            )

    def forward(self, input_texts):
        return self.classifier(input_texts)

In [ ]:
class EarlyStopping:
    def __init__(self, patience=5, min_delta=0.0):

        self.patience = patience
        self.min_delta = min_delta              # valore minimo di decrescita della loss di validazione all'epoca corrente
                                                # per asserire che c'è un miglioramenti della loss
        self.counter = 0                        # contatore delle epoche di pazienza
        self.early_stop = False                 # flag di early stop
        self.min_validation_loss = torch.inf    # valore corrente ottimo della loss di validazione

    def __call__(self, validation_loss):
        # chiamata in forma funzionale dell'oggetto di classe EarlySopping

        if (validation_loss + self.min_delta) >= self.min_validation_loss:  # la loss di validazione non decresce
            self.counter += 1                                               # incrementiamo il contatore delle epoche di pazienza
            if self.counter >= self.patience:
                self.early_stop = True
                print("Early stop!")
        else:                                               # c'è un miglioramento della loss:
            self.min_validation_loss = validation_loss      # consideriamo la loss corrente
                                                            # come nuova loss ottimale
            self.counter = 0                                # e azzeriamo il contatore di pazienza


In [ ]:
def gen_embeddings(input_id_text, attention_mask, lm_model):
    with torch.no_grad():
        last_hidden_states = lm_model(input_id_text, attention_mask=attention_mask).last_hidden_state
        last_hidden_states = last_hidden_states[:,0,:]
    return last_hidden_states

In [ ]:
def train_loop(model, dataloader, tokenizer, lm_model, loss, optimizer, device):
    model.train()

    epoch_acc = 0
    epoch_loss = 0

    for batch_texts, batch_labels in tqdm(dataloader, desc='training set'):

        optimizer.zero_grad()

        tokens = tokenizer(list(batch_texts), add_special_tokens=True, return_tensors='pt', padding='max_length', max_length = 512, truncation=True)
        input_id_texts = tokens['input_ids'].squeeze(1).to(device)
        mask_texts = tokens['attention_mask'].squeeze(1).to(device)
        batch_labels = batch_labels.to(device)
        embeddings_texts = gen_embeddings(input_id_texts, mask_texts, lm_model)
        output = model(embeddings_texts)

        # la loss è una CrossEntropyLoss, al suo interno ha
        # la logsoftmax + negative log likelihood loss
        batch_loss = loss(output, batch_labels)
        batch_loss.backward()
        optimizer.step()

        epoch_loss += batch_loss.item()

        # per calcolare l'accuracy devo generare le predizioni
        # applicando manualmente la logsoftmax
        softmax = nn.LogSoftmax(dim=1)
        epoch_acc += (softmax(output).argmax(dim=1) == batch_labels).sum().item()

        batch_labels = batch_labels.detach().cpu()
        embeddings_texts = embeddings_texts.detach().cpu()
        output = output.detach().cpu()

    return epoch_loss/len(dataloader), epoch_acc

In [ ]:
def test_loop(model, dataloader, tokenizer, lm_model, loss, device):
    model.eval()

    epoch_acc = 0
    epoch_loss = 0

    with torch.no_grad():

        for batch_texts, batch_labels, in tqdm(dataloader, desc='dev set'):

            tokens = tokenizer(list(batch_texts), add_special_tokens=True,
        return_tensors='pt', padding='max_length', max_length = 512, truncation=True)
            input_id_texts = tokens['input_ids'].squeeze(1).to(device)
            mask_texts = tokens['attention_mask'].squeeze(1).to(device)
            batch_labels = batch_labels.to(device)
            embeddings_texts = gen_embeddings(input_id_texts, mask_texts, lm_model)
            output = model(embeddings_texts)

            # la loss è una CrossEntropyLoss, al suo interno ha
            # la logsoftmax + negative log likelihood loss
            batch_loss = loss(output, batch_labels)
            epoch_loss += batch_loss.item()

            # per calcolare l'accuracy devo generare le predizioni
            # applicando manualmente la logsoftmax
            softmax = nn.LogSoftmax(dim=1)
            epoch_acc += (softmax(output).argmax(dim=1) == batch_labels).sum().item()

            batch_labels = batch_labels.detach().cpu()
            embeddings_texts = embeddings_texts.detach().cpu()
            output = output.detach().cpu()

    return epoch_loss/len(dataloader), epoch_acc

In [ ]:
def train_test(model, epochs, optimizer, device, train_data, test_data,
               batch_size, model_name, train_loss_fn,
               test_loss_fn=None,         # non necessariamente train e test loss devono differire
               early_stopping=None,       # posso addstrare senza early stopping
               val_data=None,             # e in questo caso non c'è validation set
               scheduler=None):           # possibile scheduler per monitorare l'andamento di un iperparametro,
                                          # tipicamente il learning rate

    train_dataloader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True)
    val_dataloader = torch.utils.data.DataLoader(val_data, batch_size=batch_size)
    test_dataloader = torch.utils.data.DataLoader(test_data, batch_size=batch_size)

    # check sulle funzioni di loss
    if test_loss_fn == None:
        test_loss_fn = train_loss_fn

    # liste dei valori di loss e accuracy epoca per epoca per il plot
    train_loss = []
    validation_loss = []
    test_loss = []

    train_acc = []
    validation_acc = []
    test_acc = []

    config = AutoConfig.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    lm_model = AutoModel.from_pretrained(model_name, config=config).to(device)

    # Ciclo di addestramento con early stopping
    for epoch in tqdm(range(1,epochs+1)):

        epoch_train_loss, epoch_train_acc = train_loop(model, train_dataloader, tokenizer, lm_model, train_loss_fn, optimizer, device)
        train_loss.append(epoch_train_loss)
        train_acc.append(epoch_train_acc/len(train_data))

        # validation se è presente la callback di early stopping
        if early_stopping != None:
                epoch_validate_loss, epoch_validate_acc = test_loop(model,
                val_dataloader, tokenizer, lm_model, test_loss_fn, device)
                validation_loss.append(epoch_validate_loss)
                validation_acc.append(epoch_validate_acc/len(val_data))

        # test
        epoch_test_loss, epoch_test_acc,= test_loop(model, test_dataloader, tokenizer, lm_model, test_loss_fn, device)
        test_loss.append(epoch_test_loss)
        test_acc.append(epoch_test_acc/len(test_data))

        val_loss_str = f'Validation loss: {epoch_validate_loss:6.4f} ' if early_stopping != None else ' '
        val_acc_str = f'Validation accuracy: {(epoch_validate_acc/len(val_data)):6.4f} ' if early_stopping != None else ' '
        print(f"\nTrain loss: {epoch_train_loss:6.4f} {val_loss_str} Test loss: {epoch_test_loss:6.4f}")
        print(f"Train accuracy: {(epoch_train_acc/len(train_data)):6.4f} {val_acc_str}Test accuracy: {(epoch_test_acc/len(test_data)):6.4f}")

        # early stopping
        if early_stopping != None:
                early_stopping(epoch_validate_loss)
                if early_stopping.early_stop:
                    break

    return train_loss, validation_loss, test_loss, train_acc, validation_acc, test_acc

In [ ]:
# Acquisiamo il device su cui effettueremo il training
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using {device} device")

model = ClassifierDeep(len(labels_dict), hyperparameters["h_dim"], hyperparameters["dropout"]).to(device)
print(model)

# Calcoliamo il numero totale dei parametri del modello
total_params = sum(p.numel() for p in model.parameters())
print(f"Numbero totale dei parametri: {total_params}")

criterion = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=hyperparameters["learning_rate"])

# Creiamo la callback di early stopping da passare al nostro metodo di addestramento
early_stopping = EarlyStopping(patience=hyperparameters['patience'], min_delta=hyperparameters['min_delta'])

In [ ]:
# Routine di addestramento
train_loss, validation_loss,test_loss,
train_acc, validation_acc, test_acc = train_test(model, hyperparameters['epochs'], optimizer, device, train_dataset,
test_dataset, hyperparameters['batch_size'], hyperparameters['language_model'], criterion, criterion, early_stopping, val_dataset)

training set: 100%|██████████| 26/26 [00:46<00:00,  1.80s/it]

dev set: 100%|██████████| 3/3 [00:05<00:00,  1.75s/it]

 20%|██        | 1/5 [01:05<04:20, 65.16s/it]


Train loss: 0.0616 Validation loss: 0.0908  Test loss: 0.0737
Train accuracy: 0.9850 Validation accuracy: 0.9775 Test accuracy: 0.9730



training set: 100%|██████████| 26/26 [00:48<00:00,  1.86s/it]

dev set: 100%|██████████| 3/3 [00:05<00:00,  1.78s/it]

 40%|████      | 2/5 [02:12<03:18, 66.30s/it]


Train loss: 0.0326 Validation loss: 0.0843  Test loss: 0.0721
Train accuracy: 0.9925 Validation accuracy: 0.9775 Test accuracy: 0.9820



training set: 100%|██████████| 26/26 [00:48<00:00,  1.88s/it]

dev set: 100%|██████████| 3/3 [00:05<00:00,  1.81s/it]

 60%|██████    | 3/5 [03:20<02:14, 67.07s/it]


Train loss: 0.0190 Validation loss: 0.0852  Test loss: 0.0659
Train accuracy: 0.9975 Validation accuracy: 0.9719 Test accuracy: 0.9798



training set: 100%|██████████| 26/26 [00:49<00:00,  1.91s/it]

dev set: 100%|██████████| 3/3 [00:05<00:00,  1.81s/it]

 80%|████████  | 4/5 [04:28<01:07, 67.72s/it]


Train loss: 0.0101 Validation loss: 0.0994  Test loss: 0.0726
Train accuracy: 1.0000 Validation accuracy: 0.9719 Test accuracy: 0.9798



training set: 100%|██████████| 26/26 [00:49<00:00,  1.92s/it]

dev set: 100%|██████████| 3/3 [00:05<00:00,  1.83s/it]

100%|██████████| 5/5 [05:38<00:00, 67.64s/it]


Train loss: 0.0086 Validation loss: 0.0906  Test loss: 0.0676
Train accuracy: 0.9994 Validation accuracy: 0.9719 Test accuracy: 0.9775


In [ ]:
import matplotlib.pyplot as plt


fig, axs = plt.subplots(1, 2, figsize=(20, 10))

axs[0].plot(train_loss, label='training loss')
axs[0].plot(validation_loss, label='validation loss')
axs[0].plot(test_loss, label='test loss')
axs[0].legend(loc='upper right')
axs[0].set_ylim(0,1)

axs[1].plot(train_acc, label='training accuracy')
axs[1].plot(validation_acc, label='validation accuracy')
axs[1].plot(test_acc, label='test accuracy')
axs[1].legend(loc='lower right')
axs[1].set_ylim(0,1)